apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-service
  labels:
    app: todo-list-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list-service
    spec:
      containers:
        - name: todo-list-service
          image: todo-list-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
